### ISSUE TITLE
Does not compile on Mac OS X 10.11.6

### ISSUE THREAD

**Issue by worldnamer** [alexdowad/bit-twiddle#2]
Several errors. Firstly, the ulong type is not portable, I think. That's easily solved with `typedef unsigned long ulong;` The rest, I'm not so sure about. Perhaps this is a compiler flag issue?

```
Building native extensions.  This could take a while...
ERROR:  Error installing bit-twiddle-0.0.5.gem:
        ERROR: Failed to build gem native extension.

    current directory: /Users/worldnamer/.rvm/gems/ruby-2.3.1/gems/bit-twiddle-0.0.5/ext/bit_twiddle
/Users/worldnamer/.rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20170321-9058-oe6ba8.rb extconf.rb
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking for whether >> on a signed long is arithmetic shift or logical shift... arithmetic
checking for presence of __builtin_bswap16... oh yeah
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/worldnamer/.rvm/gems/ruby-2.3.1/extensions/x86_64-darwin-15/2.3.0/bit-twiddle-0.0.5/mkmf.log

current directory: /Users/worldnamer/.rvm/gems/ruby-2.3.1/gems/bit-twiddle-0.0.5/ext/bit_twiddle
make "DESTDIR=" clean

current directory: /Users/worldnamer/.rvm/gems/ruby-2.3.1/gems/bit-twiddle-0.0.5/ext/bit_twiddle
make "DESTDIR="
compiling bit_twiddle.c
bit_twiddle.c:63:39: error: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Werror,-Wshorten-64-to-32]
      if (bnum_greater(shiftdist, bits-1))
          ~~~~~~~~~~~~            ~~~~^~
bit_twiddle.c:78:8: error: unknown type name 'ulong'
static ulong
       ^
bit_twiddle.c:87:14: error: implicit conversion loses integer precision: 'long' to 'int' [-Werror,-Wshorten-64-to-32]
      return rdist;
      ~~~~~~ ^~~~~
bit_twiddle.c:92:14: error: implicit conversion loses integer precision: 'long' to 'int' [-Werror,-Wshorten-64-to-32]
      return rdist;
      ~~~~~~ ^~~~~
bit_twiddle.c:106:13: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'unsigned int' [-Werror,-Wshorten-64-to-32]
    *dest = int64;
          ~ ^~~~~
bit_twiddle.c:109:19: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'unsigned int' [-Werror,-Wshorten-64-to-32]
      *dest     = int64;
                ~ ^~~~~
bit_twiddle.c:113:15: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'unsigned int' [-Werror,-Wshorten-64-to-32]
      *dest = int64;
            ~ ^~~~~
bit_twiddle.c:117:19: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'unsigned int' [-Werror,-Wshorten-64-to-32]
      *dest     = int64;
                ~ ^~~~~
bit_twiddle.c:254:17: error: implicit conversion loses integer precision: 'long' to 'int' [-Werror,-Wshorten-64-to-32]
  int  length = RSTRING_LEN(str);
       ~~~~~~   ^~~~~~~~~~~~~~~~
/Users/worldnamer/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/ruby.h:998:6: note: expanded from macro 'RSTRING_LEN'
     RSTRING_EMBED_LEN(str) : \
     ^~~~~~~~~~~~~~~~~~~~~~
/Users/worldnamer/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/ruby.h:994:6: note: expanded from macro 'RSTRING_EMBED_LEN'
     (long)((RBASIC(str)->flags >> RSTRING_EMBED_LEN_SHIFT) & \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bit_twiddle.c:254:17: error: implicit conversion loses integer precision: 'long' to 'int' [-Werror,-Wshorten-64-to-32]
  int  length = RSTRING_LEN(str);
       ~~~~~~   ^~~~~~~~~~~~~~~~
/Users/worldnamer/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/ruby.h:999:28: note: expanded from macro 'RSTRING_LEN'
     RSTRING(str)->as.heap.len)
     ~~~~~~~~~~~~~~~~~~~~~~^~~
bit_twiddle.c:407:40: error: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Werror,-Wshorten-64-to-32]
    return ULONG2NUM(__builtin_bswap32(FIX2LONG(fnum)));
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
/Users/worldnamer/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/ruby.h:386:21: note: expanded from macro 'FIX2LONG'
#define FIX2LONG(x) RB_FIX2LONG(x)
                    ^
/Users/worldnamer/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/ruby.h:370:25: note: expanded from macro 'RB_FIX2LONG'
#define RB_FIX2LONG(x) ((long)RSHIFT((SIGNED_VALUE)(x),1))
                        ^
/Users/worldnamer/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/ruby.h:1597:35: note: expanded from macro 'ULONG2NUM'
#define ULONG2NUM(x) RB_ULONG2NUM(x)
                     ~~~~~~~~~~~~~^~
/Users/worldnamer/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/ruby.h:1582:45: note: expanded from macro 'RB_ULONG2NUM'
#define RB_ULONG2NUM(x) rb_ulong2num_inline(x)
                                            ^
bit_twiddle.c:409:64: error: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Werror,-Wshorten-64-to-32]
    return LONG2FIX((value & ~0xFFFFFFFFL) | __builtin_bswap32(value));
                                             ~~~~~~~~~~~~~~~~~ ^~~~~
/Users/worldnamer/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/ruby.h:257:29: note: expanded from macro 'LONG2FIX'
#define LONG2FIX(i) INT2FIX(i)
                            ^
/Users/worldnamer/.rvm/rubies/ruby-2.3.1/include/ruby-2.3.0/ruby/ruby.h:256:30: note: expanded from macro 'INT2FIX'
#define INT2FIX(i) (((VALUE)(i))<<1 | RUBY_FIXNUM_FLAG)
                             ^
bit_twiddle.c:461:1: error: expected ';' after expression
def_rot_helpers(8);
^
bit_twiddle.c:453:11: note: expanded from macro 'def_rot_helpers'
    ulong rotd = value_to_rotdist(rotdist, bits, bits-1); \
          ^
bit_twiddle.c:461:1: error: use of undeclared identifier 'ulong'
bit_twiddle.c:453:5: note: expanded from macro 'def_rot_helpers'
    ulong rotd = value_to_rotdist(rotdist, bits, bits-1); \
    ^
bit_twiddle.c:461:1: error: use of undeclared identifier 'rotd'
bit_twiddle.c:453:11: note: expanded from macro 'def_rot_helpers'
    ulong rotd = value_to_rotdist(rotdist, bits, bits-1); \
          ^
bit_twiddle.c:461:1: error: use of undeclared identifier 'rotd'
bit_twiddle.c:454:22: note: expanded from macro 'def_rot_helpers'
    return (value >> rotd) | (value << (-rotd & (bits-1))); \
                     ^
bit_twiddle.c:461:1: error: use of undeclared identifier 'rotd'
bit_twiddle.c:454:42: note: expanded from macro 'def_rot_helpers'
    return (value >> rotd) | (value << (-rotd & (bits-1))); \
                                         ^
bit_twiddle.c:461:1: error: expected ';' after expression
bit_twiddle.c:457:11: note: expanded from macro 'def_rot_helpers'
    ulong rotd = value_to_rotdist(rotdist, bits, bits-1); \
          ^
bit_twiddle.c:461:1: error: use of undeclared identifier 'ulong'
bit_twiddle.c:457:5: note: expanded from macro 'def_rot_helpers'
    ulong rotd = value_to_rotdist(rotdist, bits, bits-1); \
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [bit_twiddle.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/worldnamer/.rvm/gems/ruby-2.3.1/gems/bit-twiddle-0.0.5 for inspection.
Results logged to /Users/worldnamer/.rvm/gems/ruby-2.3.1/extensions/x86_64-darwin-15/2.3.0/bit-twiddle-0.0.5/gem_make.out
```

**Comment by alexdowad** [comment]
Dear John,

Thanks for your interest in my lil' gem! Sorry but I don't have a Mac to
try it on, otherwise I would fix this myself.

Could you:

1. Clone the repo.
2. Use Bundler to install dev dependencies.
3. Change every occurrence of 'ulong' to 'unsigned long'.
4. Use rake to build the extension.

Once a C compiler hits one error, the subsequent diagnostics may not be
accurate. So it is quite possible that the problem with 'ulong' is all it
is.

**Comment by worldnamer** [comment]
I'll try to get to that this weekend!

**Comment by alexdowad** [comment]
Dear John, are you still interested in helping to fix this up?

**Comment by vertis** [comment]
I hit the same error trying to install on windows

**Comment by ivanyv** [comment]
I tried changing the ulong occurrences (except the `ifndef` bit), and I get the same `implicit conversion loses precision` errors.

**Comment by alexdowad** [comment]
Ivan, thanks very much for confirming that. Let me go through all of those,
confirm that the conversion to a smaller type is valid, and then add casts
if so.

**Comment by alexdowad** [comment]
By the way... Ivan, it would help if you can also post the errors you are
getting.

**Comment by ivanyv** [comment]
```
cd tmp/x86_64-darwin16/bit_twiddle/2.4.2
/usr/bin/make
compiling ../../../../ext/bit_twiddle/bit_twiddle.c
../../../../ext/bit_twiddle/bit_twiddle.c:67:39: error: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Werror,-Wshorten-64-to-32]
      if (bnum_greater(shiftdist, bits-1))
          ~~~~~~~~~~~~            ~~~~^~
../../../../ext/bit_twiddle/bit_twiddle.c:113:19: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'unsigned int' [-Werror,-Wshorten-64-to-32]
      *dest     = int64;
                ~ ^~~~~
../../../../ext/bit_twiddle/bit_twiddle.c:117:15: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'unsigned int' [-Werror,-Wshorten-64-to-32]
      *dest = int64;
            ~ ^~~~~
../../../../ext/bit_twiddle/bit_twiddle.c:121:19: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'unsigned int' [-Werror,-Wshorten-64-to-32]
      *dest     = int64;
                ~ ^~~~~
../../../../ext/bit_twiddle/bit_twiddle.c:276:17: error: implicit conversion loses integer precision: 'long' to 'int' [-Werror,-Wshorten-64-to-32]
  int  length = RSTRING_LEN(str);
       ~~~~~~   ^~~~~~~~~~~~~~~~
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:980:6: note: expanded from macro 'RSTRING_LEN'
     RSTRING_EMBED_LEN(str) : \
     ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:976:6: note: expanded from macro 'RSTRING_EMBED_LEN'
     (long)((RBASIC(str)->flags >> RSTRING_EMBED_LEN_SHIFT) & \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../ext/bit_twiddle/bit_twiddle.c:276:17: error: implicit conversion loses integer precision: 'long' to 'int' [-Werror,-Wshorten-64-to-32]
  int  length = RSTRING_LEN(str);
       ~~~~~~   ^~~~~~~~~~~~~~~~
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:981:28: note: expanded from macro 'RSTRING_LEN'
     RSTRING(str)->as.heap.len)
     ~~~~~~~~~~~~~~~~~~~~~~^~~
../../../../ext/bit_twiddle/bit_twiddle.c:422:64: error: implicit conversion loses integer precision: 'long' to 'unsigned int' [-Werror,-Wshorten-64-to-32]
    return LONG2FIX((value & ~0xFFFFFFFFL) | __builtin_bswap32(value));
                                             ~~~~~~~~~~~~~~~~~ ^~~~~
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:234:32: note: expanded from macro 'LONG2FIX'
#define LONG2FIX(i) RB_INT2FIX(i)
                               ^
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:231:33: note: expanded from macro 'RB_INT2FIX'
#define RB_INT2FIX(i) (((VALUE)(i))<<1 | RUBY_FIXNUM_FLAG)
                                ^
../../../../ext/bit_twiddle/bit_twiddle.c:554:53: error: implicit conversion loses integer precision: 'long' to 'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
    return LONG2FIX((value & ~0xFFFFFFFFL) | rrot32(value, rotdist));
                                             ~~~~~~ ^~~~~
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:234:32: note: expanded from macro 'LONG2FIX'
#define LONG2FIX(i) RB_INT2FIX(i)
                               ^
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:231:33: note: expanded from macro 'RB_INT2FIX'
#define RB_INT2FIX(i) (((VALUE)(i))<<1 | RUBY_FIXNUM_FLAG)
                                ^
../../../../ext/bit_twiddle/bit_twiddle.c:665:51: error: implicit conversion loses integer precision: 'long' to 'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
  return LONG2FIX((value & ~0xFFFFFFFFL) | lrot32(value, rotdist));
                                           ~~~~~~ ^~~~~
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:234:32: note: expanded from macro 'LONG2FIX'
#define LONG2FIX(i) RB_INT2FIX(i)
                               ^
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:231:33: note: expanded from macro 'RB_INT2FIX'
#define RB_INT2FIX(i) (((VALUE)(i))<<1 | RUBY_FIXNUM_FLAG)
                                ^
../../../../ext/bit_twiddle/bit_twiddle.c:829:55: error: implicit conversion loses integer precision: 'long' to 'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
    return LONG2FIX((value & ~0xFFFFFFFFL) | lshift32(value, shiftdist));
                                             ~~~~~~~~ ^~~~~
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:234:32: note: expanded from macro 'LONG2FIX'
#define LONG2FIX(i) RB_INT2FIX(i)
                               ^
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:231:33: note: expanded from macro 'RB_INT2FIX'
#define RB_INT2FIX(i) (((VALUE)(i))<<1 | RUBY_FIXNUM_FLAG)
                                ^
../../../../ext/bit_twiddle/bit_twiddle.c:974:55: error: implicit conversion loses integer precision: 'long' to 'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
    return LONG2FIX((value & ~0xFFFFFFFFL) | rshift32(value, shiftdist));
                                             ~~~~~~~~ ^~~~~
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:234:32: note: expanded from macro 'LONG2FIX'
#define LONG2FIX(i) RB_INT2FIX(i)
                               ^
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:231:33: note: expanded from macro 'RB_INT2FIX'
#define RB_INT2FIX(i) (((VALUE)(i))<<1 | RUBY_FIXNUM_FLAG)
                                ^
../../../../ext/bit_twiddle/bit_twiddle.c:1119:62: error: implicit conversion loses integer precision: 'long' to 'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
    return LONG2FIX((value & ~0xFFFFFFFFUL) | arith_rshift32(value, shiftdist));
                                              ~~~~~~~~~~~~~~ ^~~~~
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:234:32: note: expanded from macro 'LONG2FIX'
#define LONG2FIX(i) RB_INT2FIX(i)
                               ^
/usr/local/opt/rbenv/versions/2.4.2/include/ruby-2.4.0/ruby/ruby.h:231:33: note: expanded from macro 'RB_INT2FIX'
#define RB_INT2FIX(i) (((VALUE)(i))<<1 | RUBY_FIXNUM_FLAG)
                                ^
../../../../ext/bit_twiddle/bit_twiddle.c:1225:31: error: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
  return ((uint64_t)reverse32(value) << 32) | reverse32(value >> 32);
                    ~~~~~~~~~ ^~~~~
../../../../ext/bit_twiddle/bit_twiddle.c:1290:20: error: implicit conversion loses integer precision: 'long' to 'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
  uint32_t lo32  = value;
           ~~~~    ^~~~~
14 errors generated.
make: *** [bit_twiddle.o] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/make...]
```

**Comment by alexdowad** [comment]
I'm trying to figure out what C compiler @ivanyv is using. The way it displays errors looks like clang, but I just tried building `bit-twiddle` with clang 3.8.0 and succeeded. Hmm....

**Comment by alexdowad** [comment]
OK, I just found that if I add `-Wconversion` to the compiler flags, I can duplicate most of the errors @ivanyv is getting...

**Comment by alexdowad** [comment]
I've just pushed some updated code with added type casts to avoid 'implicit type conversion' errors. Seeing if it will make both Travis CI and Appveyor happy...

**Comment by alexdowad** [comment]
Hmm. @ivanyv, could you try pulling the latest `master` and see if you can build the extension?

**Comment by alexdowad** [comment]
...Or if necessary, I can cut a new gem just so you can try installing it...

**Comment by ivanyv** [comment]
You're the man Alex! Compiled with flying (green) colors.

**Comment by alexdowad** [comment]
OK, let me cut a new gem.

**Comment by alexdowad** [comment]
Just released 0.0.7. @ivanyv, could you see whether `gem install bit-twiddle` works for you on OS X?

**Comment by ivanyv** [comment]
It works :)

**Comment by alexdowad** [comment]
Great! Thanks for your help in fixing this problem.
